=== shiitake/DiagManager/archive/pssdiag_schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:pssd="http://tempuri.org" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="CollectionPointType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="startup"/>
			<xs:enumeration value="shutdown"/>
			<xs:enumeration value="polled"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="WaitType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="no"/>
			<xs:enumeration value="yes"/>
			<xs:enumeration value="onlyonshutdown"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PollingIntervalType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="3599"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="MaxFileSizeType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="1024"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CollectorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="customtsqlcommand"/>
			<xs:enumeration value="customutility"/>
			<xs:enumeration value="customdiagnostic"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CustomDiagnosticType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="tsql_command"/>
			<xs:enumeration value="tsql_script"/>
			<xs:enumeration value="utility"/>
			<xs:enumeration value="vb_script"/>
			<xs:enumeration value="copy_file"/>
			<xs:enumeration value="tail_file"/>
			<xs:enumeration value="type_file"/>
			<xs:enumeration value="reg_query"/>
			<xs:enumeration value="reg_save"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="MachineCollectorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="custom"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="InstanceCollectorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="customtsqlcommand"/>
			<xs:enumeration value="customutility"/>
			<xs:enumeration value="customdiagnostic"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SSVerType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="7"/>
			<xs:maxInclusive value="9"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AuthType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Windows"/>
			<xs:enumeration value="SQLServer"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ParameterNameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[@].+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SetupVerType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CaseNumberType">
		<xs:restriction base="xs:string">
			<xs:pattern value="SR.[0-9]{12}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Collection">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Machines" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Machine" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="MachineCollectors" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="EventlogCollector" minOccurs="1" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="enabled" type="xs:boolean" default="false" form="unqualified"/>
															<xs:attribute name="startup" type="xs:boolean" default="false" form="unqualified"/>
															<xs:attribute name="shutdown" type="xs:boolean" default="false" form="unqualified"/>
														</xs:complexType>
													</xs:element>
													<xs:element name="PerfmonCollector" minOccurs="1" maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="PerfmonCounters" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="PerfmonObject" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="PerfmonCounter" maxOccurs="unbounded">
																							<xs:complexType>
																								<xs:attribute name="enabled" type="xs:boolean" default="false" form="unqualified"/>
																								<xs:attribute name="name" type="xs:string" default="" form="unqualified"/>
																							</xs:complexType>
																						</xs:element>
																					</xs:sequence>
																					<xs:attribute name="enabled" type="xs:boolean" form="unqualified"/>
																					<xs:attribute name="name" type="xs:string" default="" form="unqualified"/>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name="enabled" type="xs:boolean" default="false" form="unqualified"/>
															<xs:attribute name="pollinginterval" type="PollingIntervalType" default="5" form="unqualified"/>
															<xs:attribute name="maxfilesize" type="MaxFileSizeType" default="256" form="unqualified"/>
														</xs:complexType>
													</xs:element>
													<xs:element name="MachineCollector" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="type" type="MachineCollectorType" use="required" form="unqualified"/>
															<xs:attribute name="point" type="CollectionPointType" use="required" form="unqualified"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Instances" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Instance" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Collectors" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="SqldiagCollector" minOccurs="1" maxOccurs="1">
																				<xs:complexType>
																					<xs:attribute name="enabled" type="xs:boolean" default="false" form="unqualified"/>
																					<xs:attribute name="startup" type="xs:boolean" default="false" form="unqualified"/>
																					<xs:attribute name="shutdown" type="xs:boolean" default="false" form="unqualified"/>
																				</xs:complexType>
																			</xs:element>
																			<xs:element name="BlockingCollector" minOccurs="1" maxOccurs="1">
																				<xs:complexType>
																					<xs:attribute name="enabled" type="xs:boolean" default="false" form="unqualified"/>
																					<xs:attribute name="latch" type="xs:boolean" default="false" form="unqualified"/>
																					<xs:attribute name="fast" type="xs:boolean" default="true" form="unqualified"/>
																					<xs:attribute name="pollinginterval" type="PollingIntervalType" default="5" form="unqualified"/>
																				</xs:complexType>
																			</xs:element>
																			<xs:element name="ProfilerCollector" minOccurs="1" maxOccurs="1">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="Events" minOccurs="0">
																							<xs:complexType>
																								<xs:sequence>
																									<xs:element name="EventType" maxOccurs="unbounded">
																										<xs:complexType>
																											<xs:sequence>
																												<xs:element name="Event" maxOccurs="unbounded">
																													<xs:complexType>
																														<xs:attribute name="enabled" type="xs:boolean" default="false" form="unqualified"/>
																														<xs:attribute name="name" type="xs:string" default="" form="unqualified"/>
																														<xs:attribute name="description" type="xs:string" default="" form="unqualified"/>
																														<xs:attribute name="id" type="xs:int" default="0" form="unqualified"/>
																													</xs:complexType>
																												</xs:element>
																											</xs:sequence>
																											<xs:attribute name="enabled" type="xs:boolean" default="false" form="unqualified"/>
																											<xs:attribute name="name" type="xs:string" default="" form="unqualified"/>
																										</xs:complexType>
																									</xs:element>
																								</xs:sequence>
																							</xs:complexType>
																						</xs:element>
																					</xs:sequence>
																					<xs:attribute name="enabled" type="xs:boolean" default="false" form="unqualified"/>
																					<xs:attribute name="template" type="xs:string" default="_GeneralPerformance80.TTD" form="unqualified"/>
																					<xs:attribute name="pollinginterval" type="PollingIntervalType" default="5" form="unqualified"/>
																					<xs:attribute name="maxfilesize" type="MaxFileSizeType" default="350" form="unqualified"/>
																				</xs:complexType>
																			</xs:element>
																			<xs:element name="Collector" minOccurs="0" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:attribute name="enabled" type="xs:boolean" default="false" form="unqualified"/>
																					<xs:attribute name="type" type="InstanceCollectorType" default="customutility" form="unqualified"/>
																					<xs:attribute name="point" type="CollectionPointType" default="startup" form="unqualified"/>
																					<xs:attribute name="cmd" type="xs:string" default="" form="unqualified"/>
																					<xs:attribute name="groupname" type="xs:string" default="" form="unqualified"/>
																					<xs:attribute name="taskname" type="xs:string" default="" form="unqualified"/>
																					<xs:attribute name="customdiagtype" type="CustomDiagnosticType" default="utility" form="unqualified"/>
																					<xs:attribute name="wait" type="WaitType" default="no" form="unqualified"/>
																				</xs:complexType>
																			</xs:element>
																			<xs:element name="CustomDiagGroup" minOccurs="0" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:attribute name="enabled" type="xs:boolean" default="false" form="unqualified"/>
																					<xs:attribute name="name" type="xs:string" default="" form="unqualified"/>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name="name" type="xs:string" default="*" form="unqualified"/>
															<xs:attribute name="windowsauth" type="xs:boolean" default="true" form="unqualified"/>
															<xs:attribute name="ssver" type="SSVerType" default="8" form="unqualified"/>
															<xs:attribute name="user" type="xs:string" default="" form="unqualified"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
											<xs:unique name="UniqueInstanceName">
												<xs:selector xpath=".//Instance"/>
												<xs:field xpath="@name"/>
											</xs:unique>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" default="" form="unqualified"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="UniqueMachineName">
						<xs:selector xpath=".//Machine"/>
						<xs:field xpath="@name"/>
					</xs:unique>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="setupver" type="SetupVerType" form="unqualified"/>
			<xs:attribute name="casenumber" type="CaseNumberType" form="unqualified" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== shiitake/DiagManager/pssdiag.xml
<?xml version="1.0" ?>
<Collection setupver="3.0.1.7" casenumber="SRX000000000000" xmlns:pssd="http://tempuri.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="pssdiag_schema.xsd">
	<Machines>
		<Machine name=".">
			<MachineCollectors>
				<EventlogCollector enabled="true" startup="false" shutdown="true" />
				<PerfmonCollector enabled="true" pollinginterval="5" maxfilesize="256">
					<PerfmonCounters>
						<PerfmonObject name="\MSSQL$%s:Buffer Manager" enabled="true">
							<PerfmonCounter name="\Buffer cache hit ratio" enabled="true" />
							<PerfmonCounter name="\Buffer cache hit ratio base" enabled="true" />
							<PerfmonCounter name="\Page lookups/sec" enabled="true" />
							<PerfmonCounter name="\Free list stalls/sec" enabled="true" />
							<PerfmonCounter name="\Free pages" enabled="true" />
							<PerfmonCounter name="\Total pages" enabled="true" />
							<PerfmonCounter name="\Target pages" enabled="true" />
							<PerfmonCounter name="\Database pages" enabled="true" />
							<PerfmonCounter name="\Reserved pages" enabled="true" />
							<PerfmonCounter name="\Stolen pages" enabled="true" />
							<PerfmonCounter name="\Lazy writes/sec" enabled="true" />
							<PerfmonCounter name="\Readahead pages/sec" enabled="true" />
							<PerfmonCounter name="\Procedure cache pages" enabled="true" />
							<PerfmonCounter name="\Page reads/sec" enabled="true" />
							<PerfmonCounter name="\Page writes/sec" enabled="true" />
							<PerfmonCounter name="\Checkpoint pages/sec" enabled="true" />
							<PerfmonCounter name="\AWE lookup maps/sec" enabled="true" />
							<PerfmonCounter name="\AWE stolen maps/sec" enabled="true" />
							<PerfmonCounter name="\AWE write maps/sec" enabled="true" />
							<PerfmonCounter name="\AWE unmap calls/sec" enabled="true" />
							<PerfmonCounter name="\AWE unmap pages/sec" enabled="true" />
							<PerfmonCounter name="\Page life expectancy" enabled="true" />
						</PerfmonObject>
						<PerfmonObject name="\MSSQL$%s:Buffer Partition(0)" enabled="true">
							<PerfmonCounter name="\Free pages" enabled="true" />
							<PerfmonCounter name="\Free list requests/sec" enabled="true" />
							<PerfmonCounter name="\Free list empty/sec" enabled="true" />
						</PerfmonObject>
						<PerfmonObject name="\MSSQL$%s:General Statistics" enabled="true">
							<PerfmonCounter name="\Logins/sec" enabled="true" />
							<PerfmonCounter name="\Logouts/sec" enabled="true" />
							<PerfmonCounter name="\User Connections" enabled="true" />
						</PerfmonObject>
						<PerfmonObject name="\MSSQL$%s:Locks(Extent)" enabled="true">
							<PerfmonCounter name="\Lock Requests/sec" enabled="true" />
							<PerfmonCounter name="\Lock Timeouts/sec" enabled="true" />
							<PerfmonCounter name="\Number of Deadlocks/sec" enabled="true" />
							<PerfmonCounter name="\Lock Waits/sec" enabled="true" />
							<PerfmonCounter name="\Lock Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time Base" enabled="true" />
						</PerfmonObject>
						<PerfmonObject name="\MSSQL$%s:Locks(Key)" enabled="true">
							<PerfmonCounter name="\Lock Requests/sec" enabled="true" />
							<PerfmonCounter name="\Lock Timeouts/sec" enabled="true" />
							<PerfmonCounter name="\Number of Deadlocks/sec" enabled="true" />
							<PerfmonCounter name="\Lock Waits/sec" enabled="true" />
							<PerfmonCounter name="\Lock Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time Base" enabled="true" />
						</PerfmonObject>
						<PerfmonObject name="\MSSQL$%s:Locks(Page)" enabled="true">
							<PerfmonCounter name="\Lock Requests/sec" enabled="true" />
							<PerfmonCounter name="\Lock Timeouts/sec" enabled="true" />
							<PerfmonCounter name="\Number of Deadlocks/sec" enabled="true" />
							<PerfmonCounter name="\Lock Waits/sec" enabled="true" />
							<PerfmonCounter name="\Lock Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time Base" enabled="true" />
						</PerfmonObject>
						<PerfmonObject name="\MSSQL$%s:Locks(Table)" enabled="true">
							<PerfmonCounter name="\Lock Requests/sec" enabled="true" />
							<PerfmonCounter name="\Lock Timeouts/sec" enabled="true" />
							<PerfmonCounter name="\Number of Deadlocks/sec" enabled="true" />
							<PerfmonCounter name="\Lock Waits/sec" enabled="true" />
							<PerfmonCounter name="\Lock Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time Base" enabled="true" />
						</PerfmonObject>
						<PerfmonObject name="\MSSQL$%s:Locks(RID)" enabled="true">
							<PerfmonCounter name="\Lock Requests/sec" enabled="true" />
							<PerfmonCounter name="\Lock Timeouts/sec" enabled="true" />
							<PerfmonCounter name="\Number of Deadlocks/sec" enabled="true" />
							<PerfmonCounter name="\Lock Waits/sec" enabled="true" />
							<PerfmonCounter name="\Lock Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time Base" enabled="true" />
						</PerfmonObject>
						<PerfmonObject name="\MSSQL$%s:Locks(Database)" enabled="true">
							<PerfmonCounter name="\Lock Requests/sec" enabled="true" />
							<PerfmonCounter name="\Lock Timeouts/sec" enabled="true" />
							<PerfmonCounter name="\Number of Deadlocks/sec" enabled="true" />
							<PerfmonCounter name="\Lock Waits/sec" enabled="true" />
							<PerfmonCounter name="\Lock Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time Base" enabled="true" />
						</PerfmonObject>
						<PerfmonObject name="\MSSQL$%s:Locks(_Total)" enabled="true">
							<PerfmonCounter name="\Lock Requests/sec" enabled="true" />
							<PerfmonCounter name="\Lock Timeouts/sec" enabled="true" />
							<PerfmonCounter name="\Number of Deadlocks/sec" enabled="true" />
							<PerfmonCounter name="\Lock Waits/sec" enabled="true" />
							<PerfmonCounter name="\Lock Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Wait Time Base" enabled="true" />
						</PerfmonObject>
						<PerfmonObject name="\MSSQL$%s:Databases(*)" enabled="true">
							<PerfmonCounter name="\Data File(s) Size (KB)" enabled="true" />
							<PerfmonCounter name="\Log File(s) Size (KB)" enabled="true" />
							<PerfmonCounter name="\Log File(s) Used Size (KB)" enabled="true" />
							<PerfmonCounter name="\Percent Log Used" enabled="true" />
							<PerfmonCounter name="\Active Transactions" enabled="true" />
							<PerfmonCounter name="\Transactions/sec" enabled="true" />
							<PerfmonCounter name="\Repl. Pending Xacts" enabled="true" />
							<PerfmonCounter name="\Repl. Trans. Rate" enabled="true" />
							<PerfmonCounter name="\Log Cache Reads/sec" enabled="true" />
							<PerfmonCounter name="\Log Cache Hit Ratio" enabled="true" />
							<PerfmonCounter name="\Log Cache Hit Ratio Base" enabled="true" />
							<PerfmonCounter name="\Bulk Copy Rows/sec" enabled="true" />
							<PerfmonCounter name="\Bulk Copy Throughput/sec" enabled="true" />
							<PerfmonCounter name="\Backup/Restore Throughput/sec" enabled="true" />
							<PerfmonCounter name="\DBCC Logical Scan Bytes/sec" enabled="true" />
							<PerfmonCounter name="\Shrink Data Movement Bytes/sec" enabled="true" />
							<PerfmonCounter name="\Log Flushes/sec" enabled="true" />
							<PerfmonCounter name="\Log Bytes Flushed/sec" enabled="true" />
							<PerfmonCounter name="\Log Flush Waits/sec" enabled="true" />
							<PerfmonCounter name="\Log Flush Wait Time" enabled="true" />
							<PerfmonCounter name="\Log Truncations" enabled="true" />
							<PerfmonCounter name="\Log Growths" enabled="true" />
							<PerfmonCounter name="\Log Shrinks" enabled="true" />
						</PerfmonObject>
						<PerfmonObject name="\MSSQL$%s:Latches" enabled="true">
							<PerfmonCounter name="\Latch Waits/sec" enabled="true" />
							<PerfmonCounter name="\Average Latch Wait Time (ms)" enabled="true" />
							<PerfmonCounter name="\Average Latch Wait Time Base" enabled="true" />
							<PerfmonCounter name="\Total Latch Wait Time (ms)" enabled="true" />
						</PerfmonObject>
						<PerfmonObject name="\MSSQL$%s:Access Methods" enabled="true">
							<PerfmonCounter name="\Full Scans/sec" enabled="true" />
							<PerfmonCounter name="\Range Scans/sec" enabled="true" />
							<PerfmonCounter name="\Probe Scans/sec" enabled="true" />
							<PerfmonCounter name="\Scan Point Revalidations/sec" enabled="true" />
							<PerfmonCounter name="\Workfiles Created/sec" enabled="true" />
							<PerfmonCounter name="\Worktables Created/sec" enabled="true" />
							<PerfmonCounter name="\Worktables From Cache Ratio" enabled="true" />
							<PerfmonCounter name="\Worktables From Cache Base" enabled="true" />
							<PerfmonCounter name="\Forwarded Records/sec" enabled="true" />
							<PerfmonCounter name="\Skipped Ghosted Records/sec" enabled="true" />
							<PerfmonCounter name="\Index Searches/sec" enabled="true" />
							<PerfmonCounter name="\FreeSpace Scans/sec" enabled="true" />
							<PerfmonCounter name="\FreeSpace Page Fetches/sec" enabled="true" />
							<PerfmonCounter name="\Pages Allocated/sec" enabled="true" />
							<PerfmonCounter name="\Extents Allocated/sec" enabled="true" />
							<PerfmonCounter name="\Mixed page allocations/sec" enabled="true" />
							<PerfmonCounter name="\Extent Deallocations/sec" enabled="true" />
